#!/bin/bash
rm ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json
yarn run build:ios &&
yarn run build:android &&
code-push release-react samplingi ios -m -t "<=$1" &&
code-push release-react samplinga android -m -t "<=$1"
