# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampling' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sampling
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'samplingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sampling-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sampling-tvOS

  target 'sampling-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
